apiVersion: apps/v1
kind: Deployment
metadata:
  name: thfr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thfr
  template:
    metadata:
      labels:
        app: thfr
    spec:
      containers:
      - image: okteto.dev/thfr:latest
        name: thfr
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ea33a348-726b-4b65-8636-8e39d04a4bef"
        - name: Vless_Path
          value: "/vl715"
        - name: Vmess_UUID
          value: "ea33a348-726b-4b65-8636-8e39d04a4bef"
        - name: Vmess_Path
          value: "/vm6715"
        - name: Share_Path
          value: "/v2link"
